language: r
sudo: false
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin

notifications:
  email:
    on_success: change
    on_failure: change
