language: r

apt_packages:
- libnetcdf-dev
- netcdf-bin

r_binary_packages:
- rgdal

r_github_packages:
- jimhester/robustr
- jimhester/covr
- hadley/xml2

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: GXkm1WAyjhaG5VSHCZNHlUylQKt8ZsRtwAXmYyZr4B11eVtCWtYQw+O/fTmAeu8R/IwgTCJnDpqcmCBb+jz5uC6eJv3aXdAxalN0+G7IU/y005KdAowz12G3u13rMlnw0KYHe0tWh8IusycMZWY0xh927IylOJndTn+0hpCEEmg=
